CREATE TABLE `contacts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` text NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `subject` varchar(300) NOT NULL,
  `message` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customer_payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `payment_uuid` char(36) NOT NULL,
  `customer_id` int NOT NULL,
  `payment_date` date NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `payment_method` varchar(255) NOT NULL,
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `transactionId` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `payment_uuid` (`payment_uuid`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `customer_payments_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL,
  `middle_initial` varchar(1) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `og_id` varchar(255) NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `address` varchar(255) NOT NULL,
  `address2` varchar(100) DEFAULT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `zipcode` varchar(255) NOT NULL,
  `address_point` point DEFAULT NULL,
  `business_type` varchar(255) DEFAULT 'other',
  `business_name` varchar(255) DEFAULT NULL,
  `invoice_terms` text,
  `url_website` varchar(500) DEFAULT NULL,
  `url_yelp` varchar(500) DEFAULT NULL,
  `url_google` varchar(500) DEFAULT NULL,
  `url_twitter` varchar(500) DEFAULT NULL,
  `url_tiktok` varchar(500) DEFAULT NULL,
  `url_snap` varchar(500) DEFAULT NULL,
  `url_instagram` varchar(500) DEFAULT NULL,
  `url_facebook` varchar(500) DEFAULT NULL,
  `referred_by` varchar(100) DEFAULT NULL,
  `url_linkedin` varchar(100) DEFAULT NULL,
  `token_linkedin` varchar(500) DEFAULT NULL,
  `token_twitter_c_key` varchar(100) DEFAULT NULL,
  `token_twitter_c_secret` varchar(100) DEFAULT NULL,
  `token_twitter_a` varchar(100) DEFAULT NULL,
  `token_twitter_a_secret` varchar(100) DEFAULT NULL,
  `api_key` varchar(100) DEFAULT NULL,
  `is_email_confirmed` tinyint(1) DEFAULT NULL,
  `is_email_confirmed_code` varchar(10) DEFAULT NULL,
  `is_phone_confirmed` tinyint(1) DEFAULT NULL,
  `is_phone_confirmed_code` varchar(10) DEFAULT NULL,
  `password_reset_code` varchar(10) DEFAULT NULL,
  `twilio_voice_message` varchar(300) DEFAULT NULL,
  `license_no` varchar(25) DEFAULT NULL,
  `twilio_voice_forward_phone` varchar(45) DEFAULT NULL,
  `stripe_key` varchar(200) DEFAULT NULL,
  `stripe_key_pub` varchar(200) DEFAULT NULL,
  `stripe_fee` decimal(10,2) DEFAULT NULL,
  `sendgrid_key` varchar(100) DEFAULT NULL,
  `sendgrid_email` varchar(100) DEFAULT NULL,
  `wallet_id_private` varchar(100) DEFAULT NULL,
  `wallet_id_public` varchar(100) DEFAULT NULL,
  `wallet_id_active_nft_id` varchar(100) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `hrn_access_email` varchar(500) DEFAULT NULL,
  `push_notification_phone` varchar(300) DEFAULT NULL,
  `push_notification_email` varchar(300) DEFAULT NULL,
  `twilio_api_key` varchar(300) DEFAULT NULL,
  `twilio_sms_phone` varchar(45) DEFAULT NULL,
  `twilio_api_sid` varchar(100) DEFAULT NULL,
  `lead_pipeline_steps` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `discounts` (
  `discount_id` int NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `percentage` decimal(5,2) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`discount_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `employeetimesheet` (
  `timesheetid` int NOT NULL AUTO_INCREMENT,
  `employeeid` int NOT NULL,
  `date` date NOT NULL,
  `starttime` datetime NOT NULL,
  `endtime` datetime DEFAULT NULL,
  `hoursworked` decimal(4,2) NOT NULL,
  `username` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`timesheetid`),
  KEY `employeeid` (`employeeid`),
  CONSTRAINT `employeetimesheet_ibfk_1` FOREIGN KEY (`employeeid`) REFERENCES `technician` (`technician_id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `entity` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` text NOT NULL,
  `first_name` text NOT NULL,
  `last_name` text NOT NULL,
  `email` text NOT NULL,
  `phone` text NOT NULL,
  `address` text NOT NULL,
  `address2` varchar(50) DEFAULT NULL,
  `city` text NOT NULL,
  `state` text NOT NULL,
  `zipcode` text NOT NULL,
  `country` text,
  `birthday` date DEFAULT NULL,
  `gender` text,
  `marital_status` text,
  `nationality` text,
  `occupation` text,
  `income_range` text,
  `education_level` text,
  `preferences` text,
  `interests` text,
  `emergency_contact_name` text,
  `emergency_contact_relationship` text,
  `emergency_contact_phone` text,
  `referral_source` text,
  `loyalty_program` text,
  `loyalty_points` int DEFAULT '0',
  `facebook_username` text,
  `twitter_handle` text,
  `instagram_username` text,
  `linkedin_url` text,
  `youtube_channel` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` text NOT NULL,
  `created_date` date NOT NULL,
  `last_modified_by` text,
  `last_modified_date` timestamp NULL DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `username_entity` text,
  `mfer_uuid` varchar(100) DEFAULT NULL,
  `location_point` point DEFAULT NULL,
  `company_name` varchar(100) DEFAULT NULL,
  `display_name` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1165 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `location` text,
  `location_point` point DEFAULT NULL,
  `description` text,
  `reminder_time` datetime DEFAULT NULL,
  `invitees` text,
  `username` varchar(255) NOT NULL,
  `group_id` varchar(255) DEFAULT NULL,
  `uuid` varchar(255) DEFAULT NULL,
  `event_status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=156 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `expenses` (
  `expense_id` int NOT NULL AUTO_INCREMENT,
  `expense_date` date NOT NULL,
  `expense_description` varchar(255) NOT NULL,
  `expense_amount` decimal(10,2) NOT NULL,
  `vendor_id` int NOT NULL,
  `username` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expense_type` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`expense_id`),
  KEY `fk_expenses_vendors` (`vendor_id`),
  CONSTRAINT `fk_expenses_vendors` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `image_repository` (
  `id` int NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) DEFAULT NULL,
  `file_type` varchar(10) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `upload_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `username` varchar(255) NOT NULL,
  `order_id` int DEFAULT '0',
  `lead_id` int DEFAULT '0',
  `client_request_key` varchar(50) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `lead_correspondences` (
  `correspondence_id` int NOT NULL AUTO_INCREMENT,
  `record_id` int DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `useremail` varchar(100) DEFAULT NULL,
  `correspondence_type` varchar(50) DEFAULT NULL,
  `message` text,
  `date_created` datetime DEFAULT NULL,
  PRIMARY KEY (`correspondence_id`),
  KEY `fk_lead_correspondence_record` (`record_id`),
  CONSTRAINT `fk_lead_correspondence_record` FOREIGN KEY (`record_id`) REFERENCES `leads` (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `leads` (
  `record_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `phone` varchar(25) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `email_address` varchar(100) DEFAULT NULL,
  `lead_status` varchar(50) DEFAULT NULL,
  `changenote` varchar(50) DEFAULT NULL,
  `interconnection_status` varchar(50) DEFAULT NULL,
  `sales_notes` text,
  `link_email_address` varchar(100) DEFAULT NULL,
  `user_responsible` varchar(100) DEFAULT NULL,
  `lead_rating` varchar(10) DEFAULT NULL,
  `organization` varchar(100) DEFAULT NULL,
  `lead_source` varchar(50) DEFAULT NULL,
  `accounting_notes` text,
  `contract_amount` decimal(10,2) DEFAULT NULL,
  `financing_type` varchar(50) DEFAULT NULL,
  `cash_price` decimal(10,2) DEFAULT NULL,
  `project_notes` text,
  `dc_kw` decimal(10,2) DEFAULT NULL,
  `solar_modules` varchar(100) DEFAULT NULL,
  `solar_panel_quantity` int DEFAULT NULL,
  `inverters` varchar(100) DEFAULT NULL,
  `inverter_quantity` int DEFAULT NULL,
  `other_adders` text,
  `ev` varchar(50) DEFAULT NULL,
  `main_panel_upgrade` varchar(50) DEFAULT NULL,
  `battery` varchar(50) DEFAULT NULL,
  `meterspot_requested` varchar(50) DEFAULT NULL,
  `utility_co` varchar(100) DEFAULT NULL,
  `roof_information` varchar(255) DEFAULT NULL,
  `company_cam_link` varchar(255) DEFAULT NULL,
  `actual_closed_date` date DEFAULT NULL,
  `layout_drafted` varchar(50) DEFAULT NULL,
  `lead_created` date DEFAULT NULL,
  `date_of_last_activity` date DEFAULT NULL,
  `date_of_next_activity` date DEFAULT NULL,
  `converted_contact` varchar(100) DEFAULT NULL,
  `converted_organization` varchar(100) DEFAULT NULL,
  `converted_opportunity` varchar(100) DEFAULT NULL,
  `username` varchar(45) DEFAULT NULL,
  `useremail` varchar(100) DEFAULT NULL,
  `external_id` varchar(100) DEFAULT NULL,
  `location_point` point DEFAULT NULL,
  `lname` varchar(100) DEFAULT NULL,
  `pipelinestatus` varchar(100) DEFAULT NULL,
  `ts_c` timestamp NULL DEFAULT NULL,
  `ts_u` timestamp NULL DEFAULT NULL,
  `ts_d` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2994 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `opportunities` (
  `recordid` int NOT NULL AUTO_INCREMENT,
  `has_a_project_been_created` varchar(10) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  `converted_from_lead` varchar(10) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `interconnection_status` varchar(255) DEFAULT NULL,
  `phone_number` varchar(100) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `linked_email_address` varchar(255) DEFAULT NULL,
  `wifi_information` varchar(255) DEFAULT NULL,
  `sales_notes` text,
  `probability_of_winning` decimal(5,2) DEFAULT NULL,
  `user_responsible` varchar(255) DEFAULT NULL,
  `current_state` varchar(255) DEFAULT NULL,
  `site_evaluation` varchar(255) DEFAULT NULL,
  `utility_co` varchar(255) DEFAULT NULL,
  `dc_kw` decimal(8,2) DEFAULT NULL,
  `solar_modules` varchar(255) DEFAULT NULL,
  `inverters` varchar(255) DEFAULT NULL,
  `solar_panel_quantity` int DEFAULT NULL,
  `inverter_quantity` int DEFAULT NULL,
  `main_panel_upgrade` varchar(255) DEFAULT NULL,
  `other_adders` varchar(255) DEFAULT NULL,
  `company_cam_link` varchar(255) DEFAULT NULL,
  `date_of_next_activity` date DEFAULT NULL,
  `date_of_last_activity` date DEFAULT NULL,
  `battery` varchar(255) DEFAULT NULL,
  `financing_type` varchar(255) DEFAULT NULL,
  `accounting_notes` text,
  `roofing_price` decimal(10,2) DEFAULT NULL,
  `opportunity_value` decimal(10,2) DEFAULT NULL,
  `cash_price` decimal(10,2) DEFAULT NULL,
  `contract_amount` decimal(10,2) DEFAULT NULL,
  `actual_close_date` date DEFAULT NULL,
  `opportunity_created` date DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `useremail` varchar(255) DEFAULT NULL,
  `datetimecreated` datetime DEFAULT NULL,
  `external_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`recordid`)
) ENGINE=InnoDB AUTO_INCREMENT=221 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` varchar(45) DEFAULT NULL,
  `customer_approval_status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_id` (`order_id`),
  KEY `customer_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=119 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_discounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `discount_id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `order_id` (`order_id`),
  KEY `discount_id` (`discount_id`),
  CONSTRAINT `order_discounts_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`),
  CONSTRAINT `order_discounts_ibfk_2` FOREIGN KEY (`discount_id`) REFERENCES `discounts` (`discount_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_rebates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `rebate_id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `order_id` (`order_id`),
  KEY `rebate_id` (`rebate_id`),
  CONSTRAINT `order_rebates_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`),
  CONSTRAINT `order_rebates_ibfk_2` FOREIGN KEY (`rebate_id`) REFERENCES `rebates` (`rebate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `order_date` datetime NOT NULL,
  `ship_date` datetime DEFAULT NULL,
  `shipping_address` varchar(255) NOT NULL,
  `billing_address` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `order_total` decimal(10,2) NOT NULL,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` varchar(255) NOT NULL,
  `description` varchar(2000) NOT NULL,
  `shipping_address_point` point DEFAULT NULL,
  `billing_address_point` point DEFAULT NULL,
  `technician_id` int DEFAULT NULL,
  `customer_id` int DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `uuid` varchar(50) DEFAULT NULL,
  `shipping_address_est_price` decimal(10,2) DEFAULT NULL,
  `shipping_address_last_sale_price` decimal(10,2) DEFAULT NULL,
  `shipping_address_est_price_high` decimal(10,2) DEFAULT NULL,
  `shipping_address_est_price_low` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=192 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `order_technicians` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `technician_id` int NOT NULL,
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `event_id` int NOT NULL,
  `is_accepted_by_customer` tinyint(1) NOT NULL DEFAULT '0',
  `is_accepted_by_technician` tinyint(1) NOT NULL DEFAULT '0',
  `is_draft` tinyint(1) NOT NULL DEFAULT '1',
  `username` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_id` (`order_id`),
  KEY `technician_id` (`technician_id`),
  KEY `event_id` (`event_id`)
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment_posts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payment_id` int NOT NULL,
  `post_date` datetime NOT NULL,
  `expected_post_date` date NOT NULL,
  `effective_date` datetime NOT NULL,
  `payment_amount` decimal(10,2) NOT NULL,
  `created_at` datetime NOT NULL,
  `last_updated_at` datetime NOT NULL,
  `username` varchar(255) NOT NULL,
  `last_modified_by` int NOT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `order_customers_Id` int NOT NULL,
  `order_id` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `payment_date` datetime NOT NULL,
  `expected_post_date` date NOT NULL,
  `effective_date` datetime NOT NULL,
  `payment_amount` decimal(10,2) NOT NULL,
  `payment_method` varchar(255) NOT NULL,
  `has_cleared` tinyint(1) NOT NULL,
  `has_reversed` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `last_updated_at` datetime NOT NULL,
  `username` varchar(255) NOT NULL,
  `last_modified_by` int NOT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `payment_uuid` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `entity` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=84 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_line_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `invoice_id` int NOT NULL,
  `product_id` int NOT NULL,
  `quantity` int NOT NULL,
  `price` decimal(10,0) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` text,
  `modified_by` text,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `is_excluding` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `invoice_id` (`invoice_id`),
  KEY `product_id` (`product_id`),
  CONSTRAINT `product_line_items_ibfk_1` FOREIGN KEY (`invoice_id`) REFERENCES `orders` (`order_id`),
  CONSTRAINT `product_line_items_ibfk_2` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sku` text NOT NULL,
  `name` text NOT NULL,
  `inventory` int DEFAULT '0',
  `reorder_level` int DEFAULT '0',
  `lead_time` int DEFAULT NULL,
  `featured` tinyint(1) DEFAULT '0',
  `rating` decimal(10,0) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `category_id` int DEFAULT NULL,
  `manufacturer_id` int DEFAULT NULL,
  `availability` tinyint(1) DEFAULT '1',
  `weight` decimal(10,0) DEFAULT NULL,
  `dimensions` varchar(255) DEFAULT NULL,
  `customer_id` varchar(45) DEFAULT NULL,
  `price` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `products_chk_1` CHECK ((`inventory` >= 0))
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `projects` (
  `record_id` int NOT NULL AUTO_INCREMENT,
  `project_name` varchar(255) DEFAULT NULL,
  `phone_number` varchar(100) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `email_or_contact_information` varchar(255) DEFAULT NULL,
  `interconnection_status` varchar(100) DEFAULT NULL,
  `projects_status` varchar(100) DEFAULT NULL,
  `wifi_information` varchar(255) DEFAULT NULL,
  `wifi_network` varchar(100) DEFAULT NULL,
  `wifi_password` varchar(100) DEFAULT NULL,
  `project_notes` text,
  `user_responsible` varchar(255) DEFAULT NULL,
  `projects_description` text,
  `install_date` date DEFAULT NULL,
  `projects_organization` varchar(255) DEFAULT NULL,
  `site_evaluation` varchar(100) DEFAULT NULL,
  `project_created` date DEFAULT NULL,
  `meterspot_requested` varchar(100) DEFAULT NULL,
  `layout_drafted` varchar(100) DEFAULT NULL,
  `plans_drafted` varchar(100) DEFAULT NULL,
  `submitted_to_permitting` varchar(100) DEFAULT NULL,
  `sales_notes` text,
  `other_adders` varchar(255) DEFAULT NULL,
  `company_cam_link` varchar(255) DEFAULT NULL,
  `utility_co` varchar(100) DEFAULT NULL,
  `roof_information` varchar(255) DEFAULT NULL,
  `solar_modules` varchar(255) DEFAULT NULL,
  `inverters` varchar(255) DEFAULT NULL,
  `dc_kw` decimal(10,2) DEFAULT NULL,
  `solar_panel_quantity` int DEFAULT NULL,
  `inverter_quantity` int DEFAULT NULL,
  `battery` varchar(100) DEFAULT NULL,
  `sgip_rebate` decimal(10,2) DEFAULT NULL,
  `sgip_rebate_type` varchar(100) DEFAULT NULL,
  `sgip_rebate_status` varchar(100) DEFAULT NULL,
  `main_panel_upgrade` varchar(100) DEFAULT NULL,
  `breaker_type_needed` varchar(100) DEFAULT NULL,
  `downsize_needed` varchar(100) DEFAULT NULL,
  `is_ev` varchar(100) DEFAULT NULL,
  `sub_panel` varchar(100) DEFAULT NULL,
  `panel_description` text,
  `inspection_date` date DEFAULT NULL,
  `inspection_passed` varchar(100) DEFAULT NULL,
  `reinspection_date` date DEFAULT NULL,
  `placard_status` varchar(100) DEFAULT NULL,
  `placards_in_possession` varchar(100) DEFAULT NULL,
  `ac_disco_placards_needed` varchar(100) DEFAULT NULL,
  `inspection_tech` varchar(100) DEFAULT NULL,
  `accounting_notes` text,
  `roofing_price` decimal(10,2) DEFAULT NULL,
  `other_adders_price` decimal(10,2) DEFAULT NULL,
  `contract_amount` decimal(10,2) DEFAULT NULL,
  `cash_price` decimal(10,2) DEFAULT NULL,
  `financing_type` varchar(100) DEFAULT NULL,
  `m1_amount` decimal(10,2) DEFAULT NULL,
  `m1_payment_requested` decimal(10,2) DEFAULT NULL,
  `payment_received_m1` decimal(10,2) DEFAULT NULL,
  `m2_amount` decimal(10,2) DEFAULT NULL,
  `m2_payment_requested` decimal(10,2) DEFAULT NULL,
  `payment_received_m2` decimal(10,2) DEFAULT NULL,
  `is_sales_commissions_paid` varchar(100) DEFAULT NULL,
  `actual_close_date` date DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `useremail` varchar(255) DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `external_id` varchar(45) DEFAULT NULL,
  `inspection_passed_date` datetime DEFAULT NULL,
  `sgip_rebate_string` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=535 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `quotes` (
  `request_id` int NOT NULL AUTO_INCREMENT,
  `customer_name` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `request_date` date DEFAULT NULL,
  `product_name` varchar(100) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `additional_notes` text,
  `installation_address` varchar(200) DEFAULT NULL,
  `roof_type` varchar(100) DEFAULT NULL,
  `avg_monthly_energy_usage` int DEFAULT NULL,
  `additional_message` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `username` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`request_id`)
) ENGINE=InnoDB AUTO_INCREMENT=86 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rebates` (
  `rebate_id` int NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(500) NOT NULL,
  `percentage` decimal(5,2) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`rebate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `rating` int NOT NULL,
  `comment` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `token_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscriptions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` text NOT NULL,
  `email` varchar(255) NOT NULL,
  `subscribed_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `source` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `technician` (
  `technician_id` int NOT NULL AUTO_INCREMENT,
  `technician_name` text NOT NULL,
  `technician_email` text NOT NULL,
  `technician_phone` text NOT NULL,
  `technician_skills` text,
  `date_last_modified` datetime NOT NULL,
  `is_technician_active` tinyint(1) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `technician_interviewed` tinyint(1) DEFAULT NULL,
  `technician_passed_background_check` tinyint(1) DEFAULT NULL,
  `technician_payrate` decimal(10,2) NOT NULL,
  `technician_location` text,
  `technician_certifications` text,
  `technician_availability` text,
  `technician_notes` text,
  `technician_photo` blob,
  `technician_password` text,
  `username` varchar(255) DEFAULT NULL,
  `t_u` varchar(100) DEFAULT NULL,
  `t_p` varchar(45) DEFAULT NULL,
  `technician_is_working` tinyint(1) DEFAULT NULL,
  `wallet_id_private` varchar(100) DEFAULT NULL,
  `wallet_id_public` varchar(100) DEFAULT NULL,
  `wallet_id_active_nft_id` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`technician_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `attachments` varchar(255) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_public` tinyint(1) NOT NULL DEFAULT '1',
  `username` varchar(255) NOT NULL,
  `message_quick_view` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=877 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_profile` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `username` varchar(50) NOT NULL,
  `useremail` varchar(100) NOT NULL,
  `date_created` date NOT NULL,
  `settings` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vendors` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `is_approved` tinyint(1) DEFAULT '0',
  `time_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `time_updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` varchar(50) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
